apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.tracker.label.name }}'
  labels:
    app: '{{ .Values.tracker.label.name }}'
spec:
  ports:
  - port: {{ .Values.tracker.service.port }}
    protocol: TCP
    targetPort: {{ .Values.tracker.container.port }}
  selector:
    app: '{{ .Values.tracker.label.name }}'
  type: '{{ .Values.tracker.service.type }}'