apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: covidtracker
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: "{{ .Values.tracker.label.name }}"
              servicePort: { { .Values.tracker.service.port } }
